In [1]:
# 필요한 라이브러리를 불러옵니다.
import numpy as np

### 1. 값이 10~49인 numpy array를 만드세요

In [7]:
z = np.arange(10, 50)
print(z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


### 2. z를 반전하세요.

In [9]:
z = z[::-1]
print(z)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


### 3. 반전시킨 z 매트릭스를 10 x 4 매트릭스로 바꾸세요.

In [10]:
z = z.reshape(10, 4)
print(z)

[[49 48 47 46]
 [45 44 43 42]
 [41 40 39 38]
 [37 36 35 34]
 [33 32 31 30]
 [29 28 27 26]
 [25 24 23 22]
 [21 20 19 18]
 [17 16 15 14]
 [13 12 11 10]]


### 4. x에서 0이 아닌 요소의 색인을 찾아보세요.

In [13]:
x = np.array([5,6,8,0,1,0,7])
nz_idx = x[x != 0]
print(nz_idx)

[5 6 8 1 7]


### nan 값 이해하기



In [14]:
print(np.nan == np.nan)
print(np.isnan(np.nan))

import math
print(0.3 == 3 * 0.1)
print(math.isclose(0.1 + 0.2, 0.3))

False
True
False
True


### 5. 12 x 12 매트릭스를 만들어 바둑판 패턴으로 0과 1을 채우세요

In [17]:
x = np.zeros((12, 12))
print(x, end='\n\n')
###############
# 슬라이싱을 사용하세요
for i in range(0, len(x)):
    if i % 2 == 0:
        x[i:i+1, 1::2] = 1
    else:
        x[i:i+1, ::2] = 1
###############
print(x)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]

[[0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0.]]


### 6. np.tile 을 이용해서 동일한 바둑판 배턴을 만들어보세요

In [23]:
x = np.tile(np.array([[0,1],[1,0]]),(6,6))
print(x)

[[0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0]]


### 7. 1차원 배열이 x에서 값이 5~10인 요소를 0으로 바꾸세요

In [24]:
x = np.array([2,5,3,8,3,34,23,7,10])
print(x)
##################
# 필터링을 사용하세요.
x[(x >= 5) & (x <= 10)] = 0
##################
print(x)

[ 2  5  3  8  3 34 23  7 10]
[ 2  0  3  0  3 34 23  0  0]


### 8. 0에서 100 사이의 값으로 크기가 10인 1차원 array를 만드세요

In [26]:
x = np.linspace(0, 100, 10)
print(x)

[  0.          11.11111111  22.22222222  33.33333333  44.44444444
  55.55555556  66.66666667  77.77777778  88.88888889 100.        ]


### 9. np.allclose() 함수를 사용하여 2개의 array가 같은지를 확인해보세요

In [28]:
A = np.array([1e10,1e-8])
B = np.array([1.00001e10,1e-9])

equal = np.allclose(A, B)
print(equal)

True


### 10. 데카르트 좌표를 나타내는 랜덤 8 x 2 행렬을 고려하여 극좌표로 변환해보세요.

In [29]:
coord = np.random.random((10,2))
x, y = coord[:,0], coord[:,1]
r = 
theta = 
ploar_coord = np.concatenate([r[:,np.newaxis], theta[:,np.newaxis]],axis=1)
print(ploar_coord)

[0.16800776 0.43096017 0.86037895 0.97595223 0.96538911 0.71151621
 0.98297866 0.48336823 0.32213903 0.65164579] [0.72018817 0.32036147 0.48443732 0.05320422 0.50914248 0.2599187
 0.30821369 0.9750941  0.26456044 0.84118031]
